---
- name: Install dotfiles to the home directory
  hosts: localhost
  become: false
  vars:
    git_name: Fedor Ivanov
    git_email: ivnfedor@gmail.com
  # vars_prompt:
  #   - name: gpg_key_id
  #     prompt: "Enter your GPG key ID"
  #     private: false
  tasks:
    - name: Template .gitconfig
      ansible.builtin.template:
        src: ../.gitconfig
        dest: "{{ ansible_env.HOME }}/.gitconfig"

    # - name: Install oh-my-zsh
    #   ansible.builtin.copy:

    # - name: Rsync dotfiles to the home directory
    #   ansible.posix.synchronize:
    #     src: "{{ item }}"
    #     dest: "{{ ansible_env.HOME }}/"
    #     recursive: yes
    #   loop:
    #     - .gitconfig
